apiVersion: apps/v1
kind: Deployment
metadata:
  name: small-app-v2.0.0
  labels:
    app: small-app
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: small-app
      track: canary
  template:
    metadata:
      labels:
        app: small-app
        track: canary
    spec:
      containers:
        - name: small-app
          image: small-app:2.0.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 1
